name: Test
on:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE.md'
      - '**/.*'
      - docs/**
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE.md'
      - '**/.*'
      - docs/**

# Cancel previous runs of the same workflow on the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test archive-wasm
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          platforms: linux/amd64
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Build and test archive-wasm
        run: |
          set -euxo pipefail

          npm i
          npm run buildtest
