name: Test
on:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE.md'
      - '**/.*'
      - docs/**
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE.md'
      - '**/.*'
      - docs/**

# Cancel previous runs of the same workflow on the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test archive-wasm
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          platforms: linux/amd64
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Install test dependencies
        run: |
          set -euxo pipefail

          sudo apt-get update
          sudo apt-get install -y \
            zip \
            xz-utils \
            lz4 \
            gzip \
            lzop \
            zstd \
            bzip2 \
            libarchive-tools \
            xorriso \
            pax

          curl -L "https://www.rarlab.com/rar/rarlinux-x64-701.tar.gz" \
          | tar -xzf- -C "${HOME}"

          mv "${HOME}/rar"/{rar,unrar} /usr/bin
          mv "${HOME}/rar/default.sfx" /usr/lib/default.sfx

          curl -L "https://www.7-zip.org/a/7z2407-linux-x64.tar.xz" \
          | tar -xJf- -C "$HOME"

          mv "$HOME"/{7zz,7zzs} /usr/bin

      - name: Build and test archive-wasm
        run: |
          set -euxo pipefail

          npm i
          npm run buildtest
